[
   Document                          -- _1,
   Document.1:iter-star              -- _1,
   HRStar                            -- KW["*"] _1 KW["*"] _2 KW["*"] _3 _4,
   HRMinus                           -- KW["-"] _1 KW["-"] _2 KW["-"] _3 _4,
   HRPlus                            -- KW["+"] _1 KW["+"] _2 KW["+"] _3 _4,
   H1                                -- KW["#"] _1 _2,
   H1.1:opt                          -- _1,
   H1.1:opt.1:seq                    -- KW[" "] _1 _2,
   H1.1:opt.1:seq.2:opt              -- _1,
   H1.1:opt.1:seq.2:opt.1:seq        -- _1 _2,
   H1.1:opt.1:seq.2:opt.1:seq.1:iter -- KW["#"],
   H2                                -- KW["##"] _1 _2,
   H2.1:opt                          -- _1,
   H2.1:opt.1:seq                    -- KW[" "] _1 _2,
   H2.1:opt.1:seq.2:opt              -- _1,
   H2.1:opt.1:seq.2:opt.1:seq        -- _1 _2,
   H2.1:opt.1:seq.2:opt.1:seq.1:iter -- KW["#"],
   H3                                -- KW["###"] _1 _2,
   H3.1:opt                          -- _1,
   H3.1:opt.1:seq                    -- KW[" "] _1 _2,
   H3.1:opt.1:seq.2:opt              -- _1,
   H3.1:opt.1:seq.2:opt.1:seq        -- _1 _2,
   H3.1:opt.1:seq.2:opt.1:seq.1:iter -- KW["#"],
   H4                                -- KW["####"] _1 _2,
   H4.1:opt                          -- _1,
   H4.1:opt.1:seq                    -- KW[" "] _1 _2,
   H4.1:opt.1:seq.2:opt              -- _1,
   H4.1:opt.1:seq.2:opt.1:seq        -- _1 _2,
   H4.1:opt.1:seq.2:opt.1:seq.1:iter -- KW["#"],
   H5                                -- KW["#####"] _1 _2,
   H5.1:opt                          -- _1,
   H5.1:opt.1:seq                    -- KW[" "] _1 _2,
   H5.1:opt.1:seq.2:opt              -- _1,
   H5.1:opt.1:seq.2:opt.1:seq        -- _1 _2,
   H5.1:opt.1:seq.2:opt.1:seq.1:iter -- KW["#"],
   H6                                -- KW["######"] _1 _2,
   H6.1:opt                          -- _1,
   H6.1:opt.1:seq                    -- KW[" "] _1 _2,
   H6.1:opt.1:seq.2:opt              -- _1,
   H6.1:opt.1:seq.2:opt.1:seq        -- _1 _2,
   H6.1:opt.1:seq.2:opt.1:seq.1:iter -- KW["#"],
   SetextHeader                      -- _1 _2,
   H1                                -- _1 _2 _3,
   H1.1:iter                         -- KW["="],
   H2                                -- _1 _2 _3,
   H2.1:iter                         -- KW["-"],
   IndentedCodeBlock                 -- _1,
   IndentedCodeBlock.1:iter          -- _1,
   IndentedCodeChunk                 -- _1 _2,
   IndentedCodeChunk.1:iter          -- _1,
   IndentedCodeChunk.2:iter          -- _1,
   IndentedCodeChunkLine             -- KW["    "] _1 _2,
   Paragraph                         -- _1 _2,
   Paragraph.2:iter-star             -- _1,
   BlockQuote                        -- _1,
   BlockQuote.1:iter                 -- _1,
   BQBasic                           -- _1 _2,
   Item                              -- _1 _2 _3,
   Body                              -- _1,
   Body.1:iter                       -- _1,
   ListMarker                        -- _1
]